name: Documentation
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: '*'
    paths:
      - '.github/workflows/Docs.yml'
      - 'src/**'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/docs.yml'
      - 'src/**'
      - 'docs/**'
jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6 # earliest supported version
      - uses: julia-actions/cache@v2 # https://github.com/julia-actions/cache
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions 
